version: '3.8'
services:
  app:
    image: fburger/tr_chatbot:actions2
    volumes:
      - ./db_scripts:/app/db_scripts
      - ./actions:/app/actions

  rasa-production:
    volumes:
      - ./connectors:/app/connectors

  rasa-worker:
    volumes:
      - ./connectors:/app/connectors